name: tasklist_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.5
  dart_frog: ^1.0.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  firedart: ^0.9.8
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mongo_dart: ^0.10.3
  postgres: ^3.3.0
  redis: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.12
  envied_generator: ^0.5.4+1
  mocktail: ^1.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
